### ISSUE TITLE
Problem with PDF output

### ISSUE THREAD

**Issue by JamesRandom** [Arth-ur/sphinxcontrib-bitfield#3]
Hi,

I have seen issue #1. I've tried creating PDF output but the generated images are not aligned correctly: they are inline with the text and so go off the edge of the page (see attached screenshot). 
![Screenshot 2022-11-28 at 21 31 52](https://user-images.githubusercontent.com/11873471/204390195-930fab4f-1f15-4e55-a7bf-d82bf40a6cef.png)

Any idea what the problem is?

**Comment by JamesRandom** [comment]
I have just found that the output is correct if I indent the `bitfield` directive:
```
Device address

    .. bitfield::
        :bits: 10
        :lanes: 1

        [
            { "name": "A", "bits": 1},
            { "name": "R/W", "bits": 1},
            { "name": "Address", "bits": 7},
            { "name": "S", "bits": 1}
        ]
```

**Comment by Arth-ur** [comment]
Hello,

It works when the bitfield directive is indented because sphinx introduces a [quote](https://ctan.gutenberg-asso.fr/info/latex2e-help-texinfo/latex2e.html#quotation-_0026-quote) environment.

If you want to have the bitfield directive in its own paragraph, you should add the [\sphinxAtStartPar](https://www.sphinx-doc.org/en/master/latex.html#miscellany) macro with the `raw` directive or use the `container` directive:

```rst
Bitfield
========

Device address with indent

   .. bitfield::
      :bits: 10
      :lanes: 1

      [
         { "name": "A", "bits": 1},
         { "name": "R/W", "bits": 1},
         { "name": "Address", "bits": 7},
         { "name": "S", "bits": 1}
      ]

Device address with raw directive

.. raw:: latex

   \sphinxAtStartPar

.. bitfield::
   :bits: 10
   :lanes: 1

   [
      { "name": "A", "bits": 1},
      { "name": "R/W", "bits": 1},
      { "name": "Address", "bits": 7},
      { "name": "S", "bits": 1}
   ]

Device address with container

.. container:: custom

   .. bitfield::
      :bits: 10
      :lanes: 1

      [
         { "name": "A", "bits": 1},
         { "name": "R/W", "bits": 1},
         { "name": "Address", "bits": 7},
         { "name": "S", "bits": 1}
      ]
```

becomes:

![image](https://user-images.githubusercontent.com/3525811/204399467-4853d831-46d9-4986-83b2-4ab945f272d4.png)

**Comment by JamesRandom** [comment]
Thanks. That makes sense
